export const USER_ACTION_TYPES = {
    SET_CURRENT_USER : 'SET_CURRENT_USER',
    CHECK_USER_SESSION : 'CHECK_USER_SESSION',
    GOOGLE_SIGNIN_START : 'GOOGLE_SIGNIN_START',
    EMAIL_SIGNIN_START : 'EMAIL_SIGNIN_START',
    SIGNIN_SUCCESS : 'SIGNIN-SUCCESS',
    SIGNIN_FAILED: 'SIGNIN_FAILED',
    SIGNUP_START : 'SIGNUP_START',
    SIGNUP_SUCCESS : 'SIGNUP_SUCCESS',
    SIGNUP_FAILED : 'SIGNUP_FAILED',
    SIGNOUT_START : 'SIGNOUT_START',
    SIGNOUT_SUCCESS : 'SIGNOUT_SUCCESS',
    SIGNOUT_FAILED : 'SIGNOUT_FAILED'
};