export const CATEGORIES_ACTION_TYPES = {
    FETCH_CATEGORIES_SUCCESS : 'categroy/FETCH_CATEGROIES_SUCCESS',
    FETCH_CATEGORIES_FAILED : 'category/FETCH_CATEGORIES_FAILED',
    FETCH_CATEGORIES_START : 'category/FETCH_CATEGORIES_START',
}
